# Generated by Django 5.0.6 on 2024-06-07 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('education', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning')], max_length=2)),
            ],
        ),
    ]
